package tests;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Billpay feature tests — generated by TestForge from execution-verified runs.
 * Contains 1 test:
 *   - TC04 - Bill Pay Form Displays Required Fields
 */
public class BillpayTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private ParabankPage parabankPage;
    private OverviewPage overviewPage;
    private BillpayPage billpayPage;

    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized", "--disable-notifications");
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        parabankPage = new ParabankPage(driver);
        overviewPage = new OverviewPage(driver);
        billpayPage = new BillpayPage(driver);
    }

    @Test(description = "TC04 - Bill Pay Form Displays Required Fields")
    public void billPayFormDisplaysRequiredFields() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Type valid username
        parabankPage.enterUsernameInputField("john");

        // Step 3: Type valid password
        parabankPage.enterPasswordInputField("demo");

        // Step 4: Submit login form
        parabankPage.clickLoginFormSubmitButton();

        // Step 5: Click Bill Pay from left navigation menu
        overviewPage.clickBillPayNavigationLink();

        // Step 6: Assert payee name field is visible
        Assert.assertTrue(billpayPage.isPayeeNameInputFieldVisible(), "payeeNameInputField should be visible");

        // Step 7: Assert payee address field is visible
        Assert.assertTrue(billpayPage.isPayeeAddressInputFieldVisible(), "payeeAddressInputField should be visible");

        // Step 8: Assert payment amount field is visible
        Assert.assertTrue(billpayPage.isBillPaymentAmountInputFieldVisible(), "billPaymentAmountInputField should be visible");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
