package tests;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Login feature tests — generated by TestForge from execution-verified runs.
 * Contains 1 test:
 *   - TC06 - Empty Login Credentials Show Error
 */
public class LoginTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private ParabankPage parabankPage;
    private LoginPage loginPage;

    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized", "--disable-notifications");
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        parabankPage = new ParabankPage(driver);
        loginPage = new LoginPage(driver);
    }

    @Test(description = "TC06 - Empty Login Credentials Show Error")
    public void emptyLoginCredentialsShowError() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Click Login button without entering any credentials
        parabankPage.clickLoginFormSubmitButton();

        // Step 3: Assert error or login page is still shown
        Assert.assertTrue(driver.getCurrentUrl().contains("login"),
                "URL should contain 'login' but was: " + driver.getCurrentUrl());

        // Step 4: Assert error message is displayed
        Assert.assertTrue(loginPage.isLoginErrorMessageElementVisible(), "loginErrorMessageElement should be visible");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
