package tests;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Login feature tests — generated by TestForge from execution-verified runs.
 * Contains 1 test:
 *   - TC06 - Empty Login Credentials Show Error
 */
public class LoginTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private ParabankPage parabankPage;
    private LoginPage loginPage;

    @BeforeMethod
    public void setUp() {
        ChromeOptions options = new ChromeOptions();
        // On CI (GitHub Actions sets CI=true) there is no display, so run headless.
        // Locally it stays headful so you can watch; force headless with -Dheadless=true.
        boolean headless = System.getenv("CI") != null || Boolean.getBoolean("headless");
        if (headless) {
            options.addArguments("--headless=new", "--no-sandbox",
                    "--disable-dev-shm-usage", "--disable-gpu");
        }
        options.addArguments("--window-size=1920,1080", "--disable-notifications", "--remote-allow-origins=*");
        // Selenium Manager (built into Selenium 4) auto-provisions the matching driver.
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        parabankPage = new ParabankPage(driver);
        loginPage = new LoginPage(driver);
    }

    @Test(description = "TC06 - Empty Login Credentials Show Error")
    public void emptyLoginCredentialsShowError() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Click Login button without entering any credentials
        parabankPage.clickLoginFormSubmitButton();

        // Step 3: Assert error or login page is still shown
        Assert.assertTrue(driver.getCurrentUrl().contains("login"),
                "URL should contain 'login' but was: " + driver.getCurrentUrl());

        // Step 4: Assert error message is displayed
        Assert.assertTrue(loginPage.isLoginErrorMessageElementVisible(), "loginErrorMessageElement should be visible");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
