package tests;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Overview feature tests — generated by TestForge from execution-verified runs.
 * Contains 1 test:
 *   - TC07 - Accounts Overview Shows Multiple Account Links
 */
public class OverviewTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private ParabankPage parabankPage;
    private OverviewPage overviewPage;

    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized", "--disable-notifications");
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        parabankPage = new ParabankPage(driver);
        overviewPage = new OverviewPage(driver);
    }

    @Test(description = "TC07 - Accounts Overview Shows Multiple Account Links")
    public void accountsOverviewShowsMultipleAccountLinks() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Type valid username
        parabankPage.enterUsernameInputField("john");

        // Step 3: Type valid password
        parabankPage.enterPasswordInputField("demo");

        // Step 4: Submit login form
        parabankPage.clickLoginFormSubmitButton();

        // Step 5: Assert left nav shows Open New Account link
        Assert.assertTrue(overviewPage.getOpenNewAccountNavLinkText().contains("Open New Account"),
                "Expected text 'Open New Account' in openNewAccountNavLink");

        // Step 6: Assert accounts table contains at least one account link
        Assert.assertTrue(overviewPage.isAccountsTableContainerVisible(), "accountsTableContainer should be visible");

        // Step 7: Assert Total Balance row is present in accounts table
        Assert.assertTrue(overviewPage.isAccountsTableTotalRowVisible(), "accountsTableTotalRow should be visible");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
