package tests;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Parabank feature tests — generated by TestForge from execution-verified runs.
 * Contains 4 tests:
 *   - TC01 - Valid Login Lands on Accounts Overview Page
 *   - TC02 - Invalid Login Shows Error and Stays on Login Page
 *   - TC05 - Log Out Returns User to Login Page
 *   - TC08 - Navigation Links Visible on Pre-Auth Home Page
 */
public class ParabankTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private ParabankPage parabankPage;
    private OverviewPage overviewPage;
    private LoginPage loginPage;

    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized", "--disable-notifications");
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        parabankPage = new ParabankPage(driver);
        overviewPage = new OverviewPage(driver);
        loginPage = new LoginPage(driver);
    }

    @Test(description = "TC01 - Valid Login Lands on Accounts Overview Page")
    public void validLoginLandsOnAccountsOverviewPage() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Type valid username into username field
        parabankPage.enterUsernameInputField("john");

        // Step 3: Type valid password into password field
        parabankPage.enterPasswordInputField("demo");

        // Step 4: Submit the login form
        parabankPage.clickLoginFormSubmitButton();

        // Step 5: Assert page URL contains overview
        Assert.assertTrue(driver.getCurrentUrl().contains("overview"),
                "URL should contain 'overview' but was: " + driver.getCurrentUrl());

        // Step 6: Assert Accounts Overview heading is visible
        Assert.assertTrue(overviewPage.getAccountsOverviewLinkInLeftNavText().contains("Accounts Overview"),
                "Expected text 'Accounts Overview' in accountsOverviewLinkInLeftNav");

        // Step 7: Assert accounts table is displayed on overview page
        Assert.assertTrue(overviewPage.isAccountsTableContainerVisible(), "accountsTableContainer should be visible");

    }

    @Test(description = "TC02 - Invalid Login Shows Error and Stays on Login Page")
    public void invalidLoginShowsErrorAndStaysOnLoginPage() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Type valid username into username field
        parabankPage.enterUsernameInputField("john");

        // Step 3: Type incorrect password into password field
        parabankPage.enterPasswordInputField("wrongpassword123");

        // Step 4: Submit the login form
        parabankPage.clickLoginFormSubmitButton();

        // Step 5: Assert URL contains login path indicating failed auth
        Assert.assertTrue(driver.getCurrentUrl().contains("login"),
                "URL should contain 'login' but was: " + driver.getCurrentUrl());

        // Step 6: Assert error message is displayed on the page
        Assert.assertTrue(loginPage.getLoginErrorMessageElementText().contains("The username and password could not be verified"),
                "Expected text 'The username and password could not be verified' in loginErrorMessageElement");

        // Step 7: Assert username input is still visible on page
        Assert.assertTrue(loginPage.isUsernameInputFieldPostErrorVisible(), "usernameInputFieldPostError should be visible");

    }

    @Test(description = "TC05 - Log Out Returns User to Login Page")
    public void logOutReturnsUserToLoginPage() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Type valid username
        parabankPage.enterUsernameInputField("john");

        // Step 3: Type valid password
        parabankPage.enterPasswordInputField("demo");

        // Step 4: Submit login form
        parabankPage.clickLoginFormSubmitButton();

        // Step 5: Click Log Out from navigation menu
        overviewPage.clickLogOutLinkInNavigation();

        // Step 6: Assert URL contains index after logout
        Assert.assertTrue(driver.getCurrentUrl().contains("index"),
                "URL should contain 'index' but was: " + driver.getCurrentUrl());

        // Step 7: Assert username input is visible on login page
        Assert.assertTrue(parabankPage.isUsernameInputFieldVisible(), "usernameInputField should be visible");

        // Step 8: Assert login form is visible after logout
        Assert.assertTrue(parabankPage.isLoginFormElementVisible(), "loginFormElement should be visible");

    }

    @Test(description = "TC08 - Navigation Links Visible on Pre-Auth Home Page")
    public void navigationLinksVisibleOnPreAuthHomePage() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Assert About Us link is present
        Assert.assertTrue(parabankPage.isAboutUsNavigationLinkVisible(), "aboutUsNavigationLink should be visible");

        // Step 3: Assert Register link is present
        Assert.assertTrue(parabankPage.isRegisterNavigationLinkVisible(), "registerNavigationLink should be visible");

        // Step 4: Assert Forgot login info link is present
        Assert.assertTrue(parabankPage.isForgotLoginInfoLinkVisible(), "forgotLoginInfoLink should be visible");

        // Step 5: Assert Contact Us link is present in footer
        Assert.assertTrue(parabankPage.isContactUsFooterLinkVisible(), "contactUsFooterLink should be visible");

        // Step 6: Assert login form is present on the page
        Assert.assertTrue(parabankPage.isLoginFormElementVisible(), "loginFormElement should be visible");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
