package tests;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import pages.*;

import java.time.Duration;

/**
 * Transfer feature tests — generated by TestForge from execution-verified runs.
 * Contains 1 test:
 *   - TC03 - Transfer Funds Form Loads and Completes Transfer
 */
public class TransferTests {

    private WebDriver driver;
    private WebDriverWait wait;
    private ParabankPage parabankPage;
    private OverviewPage overviewPage;
    private TransferPage transferPage;

    @BeforeMethod
    public void setUp() {
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized", "--disable-notifications");
        driver = new ChromeDriver(options);
        wait = new WebDriverWait(driver, Duration.ofSeconds(15));
        parabankPage = new ParabankPage(driver);
        overviewPage = new OverviewPage(driver);
        transferPage = new TransferPage(driver);
    }

    @Test(description = "TC03 - Transfer Funds Form Loads and Completes Transfer")
    public void transferFundsFormLoadsAndCompletesTransfer() {
        // Step 1: Navigate to ParaBank home page
        driver.get("https://parabank.parasoft.com/parabank/index.htm");

        // Step 2: Type valid username
        parabankPage.enterUsernameInputField("john");

        // Step 3: Type valid password
        parabankPage.enterPasswordInputField("demo");

        // Step 4: Submit login form
        parabankPage.clickLoginFormSubmitButton();

        // Step 5: Click Transfer Funds from left navigation menu
        overviewPage.clickTransferFundsNavigationLink();

        // Step 6: Assert amount input field is visible
        Assert.assertTrue(transferPage.isTransferAmountInputFieldVisible(), "transferAmountInputField should be visible");

        // Step 7: Assert fromAccount dropdown is visible
        Assert.assertTrue(transferPage.isFromAccountDropdownVisible(), "fromAccountDropdown should be visible");

        // Step 8: Assert toAccount dropdown is visible
        Assert.assertTrue(transferPage.isToAccountDropdownVisible(), "toAccountDropdown should be visible");

        // Step 9: Enter transfer amount of 1
        transferPage.enterTransferAmountInputField("1");

        // Step 10: Click Transfer button to submit the form
        transferPage.clickTransferSubmitButton();

        // Step 11: Assert Transfer Complete confirmation message
        Assert.assertTrue(transferPage.getTransferCompleteHeadingText().contains("Transfer Complete!"),
                "Expected text 'Transfer Complete!' in transferCompleteHeading");

    }

    @AfterMethod
    public void tearDown() {
        if (driver != null) driver.quit();
    }
}
